import {floorById,filterShops,polygonPoints,visibleSideFaces} from './spatial-data.mjs';
const $=s=>document.querySelector(s),svgNS='http://www.w3.org/2000/svg';
const params=new URLSearchParams(location.search);
if(params.get('embed')==='1')document.body.classList.add('embedded');
let data,selectedFloor=null,selectedShop=null,sourcePhoto=false;
const tones={rose:'#d97979',amber:'#deb582',yellow:'#edce55',green:'#9cc270',cyan:'#5dc5d3',blue:'#7c9ee4'};
function svg(name,attributes={}){const el=document.createElementNS(svgNS,name);for(const [k,v] of Object.entries(attributes))el.setAttribute(k,String(v));return el;}
function zoneTop(floor,zone,interactive){const polygon=svg('polygon',{points:polygonPoints(zone.shape),fill:tones[zone.tone]||tones.blue,class:'shop-zone',tabindex:interactive?'0':'-1','data-zone':zone.id});
  if(interactive){polygon.setAttribute('role','button');polygon.setAttribute('aria-label',`${floor.id} 铺位色块，点击查看图上标注`);const choose=()=>selectZone(floor,zone);polygon.addEventListener('click',choose);polygon.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();choose();}});}return polygon;}
function shapeLayer(floor,interactive=false){const graphic=svg('svg',{viewBox:'40 215 1520 880',preserveAspectRatio:'xMidYMid meet'});if(!interactive)graphic.setAttribute('aria-hidden','true');
  const outline='M80 420 Q170 290 470 275 L900 235 L1335 245 Q1490 260 1530 425 L1500 805 Q1380 1010 1210 1050 L900 850 L350 760 Z';
  const depth=interactive?16:25;
  graphic.append(svg('path',{d:outline,transform:`translate(0 ${depth})`,class:'floor-plate-edge'}));
  graphic.append(svg('path',{d:outline,class:'floor-plate'}));
  for(const zone of floor.zones){const volume=svg('g',{class:'shop-volume'}),fill=tones[zone.tone]||tones.blue;
    volume.append(svg('polygon',{points:polygonPoints(zone.shape),transform:`translate(5 ${depth+7})`,class:'shop-ground-shadow'}));
    for(const face of visibleSideFaces(zone.shape,depth))volume.append(svg('polygon',{points:polygonPoints(face),fill,class:'shop-side'}));
    volume.append(zoneTop(floor,zone,interactive));graphic.append(volume);}
  return graphic;}
function renderStack(){const host=$('#stackLayers');host.replaceChildren();const reverse=[...data.floors].reverse();reverse.forEach((floor,i)=>{const button=document.createElement('button');button.type='button';button.className='stack-layer';button.style.setProperty('--level',i);button.setAttribute('aria-label',`查看 ${floor.id} 楼层`);button.append(shapeLayer(floor));const tag=document.createElement('span');tag.className='layer-tag';tag.textContent=floor.id;button.append(tag);button.onclick=()=>selectFloor(floor.id);host.append(button);});}
function renderPlan(){const floor=floorById(data,selectedFloor);if(!floor)return;$('#planFloor').textContent=floor.id;
  const canvas=$('#planSvg');canvas.replaceChildren();if(sourcePhoto){const photo=svg('image',{href:floor.photo,x:0,y:0,width:1706,height:1279,preserveAspectRatio:'none'});canvas.append(photo);}
  if(sourcePhoto){for(const zone of floor.zones){const outline=zoneTop(floor,zone,true);outline.classList.add('photo-outline');canvas.append(outline);}}
  else{const layer=shapeLayer(floor,true);canvas.append(...[...layer.children]);}
  if(!sourcePhoto){for(const shop of floor.shops){const label=svg('g',{class:'shop-label'+(selectedShop?.id===shop.id?' picked':''),tabindex:'0',role:'button','aria-label':`${shop.name}，${floor.id}${shop.confidence==='review'?'，名称待核实':''}`});const chip=svg('circle',{cx:shop.x,cy:shop.y,r:19});const text=svg('text',{x:shop.x,y:shop.y+37,'text-anchor':'middle'});text.textContent=shop.name.length>10?shop.name.slice(0,9)+'…':shop.name;label.append(chip,text);const choose=()=>selectShop(shop,floor.id);label.addEventListener('click',choose);label.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();choose();}});canvas.append(label);}}
}
function updateMode(){const inPlan=!!selectedFloor;$('#stackView').hidden=inPlan;$('#planView').hidden=!inPlan;$('#overviewBtn').classList.toggle('active',!inPlan);$('#overviewBtn').setAttribute('aria-pressed',String(!inPlan));$('#photoBtn').disabled=!inPlan;$('#photoBtn').classList.toggle('active',sourcePhoto&&inPlan);$('#photoBtn').setAttribute('aria-pressed',String(sourcePhoto&&inPlan));document.querySelectorAll('[data-floor]').forEach(b=>b.classList.toggle('active',b.dataset.floor===selectedFloor));if(inPlan)renderPlan();}
function selectFloor(id){selectedFloor=id;selectedShop=null;sourcePhoto=false;updateMode();const floor=floorById(data,id);$('#inspectorBody').replaceChildren();const kicker=document.createElement('span');kicker.className='inspector-floor';kicker.textContent=id+' / FLOOR PLAN';const heading=document.createElement('h2');heading.textContent=`${id} · 铺位概览`;const detail=document.createElement('p');detail.textContent=`从照片描出 ${floor.zones.length} 个颜色区域，读取 ${floor.shops.length} 个店名。色块交界可能合并；可点选区域或直接搜索店名。`;$('#inspectorBody').append(kicker,heading,detail);}
function renderOverviewInspector(){const body=$('#inspectorBody');body.replaceChildren();const floor=document.createElement('span');floor.className='inspector-floor';floor.textContent='B1 — 4F';const heading=document.createElement('h2');heading.innerHTML='从铺位到楼层，<br>建立空间印象。';const detail=document.createElement('p');detail.textContent='从商场导览屏照片提取颜色区域、店名和图上相对位置。选一个楼层或搜索店名查看细节。';body.append(floor,heading,detail);}
function selectShop(shop,id){if(selectedFloor!==id){selectedFloor=id;sourcePhoto=false;}selectedShop=shop;updateMode();$('#inspectorBody').replaceChildren();const kicker=document.createElement('span');kicker.className='inspector-floor';kicker.textContent=id;const heading=document.createElement('h2');heading.textContent=shop.name;const detail=document.createElement('p');detail.textContent='位置来自照片中的店铺文字；周围色块是照片提取的近似轮廓。';$('#inspectorBody').append(kicker,heading,detail);$('#searchResults').hidden=true;$('#shopSearch').value='';}
function selectZone(floor,zone){const matches=floor.shops.filter(s=>s.zoneId===zone.id);if(matches.length){const target=matches.reduce((a,b)=>(a.x-zone.center[0])**2+(a.y-zone.center[1])**2 < (b.x-zone.center[0])**2+(b.y-zone.center[1])**2?a:b);selectShop(target,floor.id);}else{selectedShop=null;$('#inspectorBody').replaceChildren();const title=document.createElement('h2');title.textContent=`${floor.id} · 未辨识铺位`;const note=document.createElement('p');note.textContent='照片中有可见色块，但店名无法可靠读取；形状与尺寸只是相对示意。';$('#inspectorBody').append(title,note);}}
function search(){const term=$('#shopSearch').value;const results=$('#searchResults');results.replaceChildren();const matches=filterShops(data,term);results.hidden=!term.trim();if(!term.trim())return;if(!matches.length){results.textContent='没有找到可读店名，可切换楼层对照原图。';return;}for(const shop of matches.slice(0,12)){const button=document.createElement('button');button.type='button';button.textContent=`${shop.floor}  ·  ${shop.name}${shop.confidence==='review'?' 〔待核〕':''}`;button.onclick=()=>selectShop(shop,shop.floor);results.append(button);}}
function showOverview(){selectedFloor=null;selectedShop=null;sourcePhoto=false;updateMode();renderOverviewInspector();}
$('#overviewBtn').onclick=showOverview;$('#backToStack').onclick=$('#overviewBtn').onclick;$('#photoBtn').onclick=()=>{sourcePhoto=!sourcePhoto;updateMode();};$('#shopSearch').oninput=search;document.querySelectorAll('[data-floor]').forEach(b=>b.onclick=()=>selectFloor(b.dataset.floor));
try{const response=await fetch('data/yintai-kiosk/kiosk-map.json');if(!response.ok)throw new Error('地图资料没有加载');data=await response.json();$('#zoneTotal').textContent=data.floors.reduce((n,f)=>n+f.zones.length,0);$('#shopTotal').textContent=data.floors.reduce((n,f)=>n+f.shops.length,0);renderStack();showOverview();}catch(error){$('#inspectorBody').textContent=`无法展示空间地图：${error.message}`;}
